const IMCartActionsConstants = {
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  OVERRIDE_CART: 'OVERRIDE_CART',
  UPDATE_ORDERS: 'UPDATE_ORDERS',
  UPDATE_CART: 'UPDATE_CART',
  SET_CART_VENDOR: 'SET_CART_VENDOR',
  ADD_PRESCRIPTION: 'ADD_PRESCRIPTION',
  REMOVE_PRESCRIPTION: 'REMOVE_PRESCRIPTION',
  OVERRIDE_PRESCRIPTIONS: 'OVERRIDE_PRESCRIPTIONS',
};

export default IMCartActionsConstants;
